services:
  - type: web
    name: spendsense-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn spendsense.app.main:app --host 0.0.0.0 --port $PORT
    postDeployCommand: python -m scripts.reset_and_populate
    envVars:
      - key: APP_ENV
        value: prod
      - key: SEED
        value: "42"
      - key: DATABASE_URL
        value: sqlite:///./data/spendsense.db
      - key: DATA_DIR
        value: ./data
      - key: PARQUET_DIR
        value: ./data/parquet
      - key: LOG_LEVEL
        value: WARNING
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: FRONTEND_PORT
        value: "5173"
